# Generated by Django 3.2 on 2021-07-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam', '0002_auto_20210709_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='file_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
